//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4
{
    using System;
    using System.Collections.Generic;
    
    public partial class empDetail
    {
        public int ID { get; set; }
        public string fname { get; set; }
        public string lname { get; set; }
        public Nullable<decimal> phoneNo { get; set; }
        public string city { get; set; }
    }
}
